using MsfsCompanion.Bridge.Aircraft;
static void Check(bool x, string reason) { if (!x) throw new Exception(reason); }
Check(AircraftProfileResolver.Resolve("Cessna 172 Skyhawk G1000").Id == "c172", "c172");
Check(AircraftProfileResolver.Resolve("CubCrafters NXCub").Id == "nxcub", "specific before general");
Check(AircraftProfileResolver.Resolve("CubCrafters XCub Floats").Id == "xcub", "xcub");
Check(AircraftProfileResolver.Resolve("Daher TBM 930").Id == "tbm930", "tbm");
Check(AircraftProfileResolver.Resolve("Airbus A320 Neo").Id == "a320-asobo-candidate", "a320 candidate");
Check(AircraftProfileResolver.Resolve("Asobo Airbus A320neo").Id == "a320-asobo-candidate", "asobo candidate");
Check(AircraftProfileResolver.Resolve("FlyByWire A32NX").Id == "airbus-addon", "fbw separated");
Check(AircraftProfileResolver.Resolve("Fenix Airbus A320").Id == "airbus-addon", "fenix separated");
Check(AircraftProfileResolver.Resolve("iniBuilds Airbus A320neo").Id == "airbus-addon", "v2 separated");
Check(AircraftProfileResolver.IsAirbusLike("A320neo"),"airbus identification");
Check(!AircraftProfileResolver.Resolve("Asobo Airbus A320neo").Verified,"unverified candidate");
var identity = new AircraftIdentityGuard();
var at = DateTimeOffset.UtcNow;
identity.Begin("Airbus A320neo",at);
Check(identity.Trusted("Airbus A320neo",at.AddSeconds(1)),"identity accepted");
identity.Observe("Cessna Skyhawk",at.AddSeconds(2));
Check(!identity.Trusted("Airbus A320neo",at.AddSeconds(3)),"aircraft change revokes trust");
identity.Observe("Airbus A320neo",at.AddSeconds(4));
Check(!identity.Trusted("Airbus A320neo",at.AddSeconds(4)),"no trust renewal after switch");
identity.Reset();
Check(!identity.Trusted("Airbus A320neo",at.AddSeconds(5)),"reset blocks control");
identity.Begin("Airbus A320neo",at);
Check(!identity.Trusted("Airbus A320neo",at.AddSeconds(11)),"stale identity cannot control");
Check(AircraftProfileResolver.Resolve("RandomAircraft").Id == "generic", "fallback");
Check(!AircraftProfileResolver.Resolve("Cessna 172").Verified, "not verified");
Console.WriteLine("PASS: aircraft profiles and generic fallback.");